# Generated by Django 4.1.4 on 2022-12-22 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="comments", old_name="create_date", new_name="created_date",
        ),
    ]
